### ISSUE TITLE
052和053

### ISSUE THREAD

**Issue by d4wner** [Lucifer1993/struts-scan#2]
话说052和053出来有段日子，也有exp了，大佬抽空可以加上唉~

**Comment by Lucifer1993** [comment]
找时间会加上去。

**Comment by flywithoutwings** [comment]
请问053的参数是什么，谢谢

**Comment by flywithoutwings** [comment]
小白还想请问为什么url后面要加个index.action，谢谢

**Comment by Lucifer1993** [comment]
example，一般都是以do和action结尾的，看具体情况，045你用域名也能检测出来。只要是struts2的路径就行，没说特定用action。

**Comment by Lucifer1993** [comment]
053的参数这个本就是不固定的，需要自己去识别。

**Comment by flywithoutwings** [comment]
请问053的参数要如何识别，谢谢
