### ISSUE TITLE
批量检查结果不保存= =尴尬！

### ISSUE THREAD

**Issue by test998998** [Lucifer1993/struts-scan#3]
批量检查结果不保存= =尴尬！

**Comment by Lucifer1993** [comment]
检测s2-053需要输入参数才能继续向下进行，所以无法将结果保存。

**Comment by gayhub-blackerie** [comment]
关于这个问题，我可以提出一个小小的修改提示：将需要输入的参数固定为字符串的格式，然后可以将结果输出为txt文本。等全过程结束后，可以使用ctrl + f 搜索漏洞情况，比如：vuln等关键字符串。谢谢lucifer大神的辛苦付出！一起加油！

**Comment by Lucifer1993** [comment]
此功能已添加。
