### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'的问题

### ISSUE THREAD

**Issue by dangshanli** [Lucifer1993/struts-scan#4]
执行python struts-scan.py [url]

报出：
  File "struts-scan.py", line 195
    print prompt,
               ^
SyntaxError: Missing parentheses in call to 'print'

是我使用的姿势不对么？

**Comment by Lucifer1993** [comment]
你用的是python3执行的吧？python2.x是不会出现这个问题的。

**Comment by FranklinYu** [comment]
建议在 README 上写一下用 Python 2？或者过渡到 Python 3？
