### ISSUE TITLE
struts2-048的检查方法实际是045的吧

### ISSUE THREAD

**Issue by ivan112058** [Lucifer1993/struts-scan#5]
struts2-048的检查方法和网上看到的045的方法差不多，和048的描述不符https://cwiki.apache.org/confluence/display/WW/S2-048

**Comment by Lucifer1993** [comment]
已完成修改。

**Comment by flywithoutwings** [comment]
不好意思，我不太明白是什么意思，还有请问053后面的参数如何识别，谢谢。






At 2017-10-25 14:02:36, "ivan112058" <notifications@github.com> wrote:


Closed #5.
