### ISSUE TITLE
请问超时是什么原因

### ISSUE THREAD

**Issue by atomoleculeliwenguang** [Lucifer1993/struts-scan#7]
检测struts2漏洞--------
目标url:http://119.254.9.210/channel/doChannelList.action
检测struts2-005超时..
超时原因:  HTTPConnectionPool(host='119.254.9.210', port=80): Max retries exceeded with url: /channel/doChannelList.action (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x191a790>, 'Connection to 119.254.9.210 timed out. (connect timeout=6)'))
检测struts2-009超时..
超时原因:  HTTPConnectionPool(host='119.254.9.210', port=80): Max retries exceeded with url: /channel/doChannelList.action (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x191afd0>, 'Connection to 119.254.9.210 timed out. (connect timeout=6)'))
检测struts2-013超时..
超时原因:  HTTPConnectionPool(host='119.254.9.210', port=80): Max retries exceeded with url: /channel/doChannelList.action (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x191af50>, 'Connection to 119.254.9.210 timed out. (connect timeout=6)'))
检测struts2-016超时..
超时原因:  HTTPConnectionPool(host='119.254.9.210', port=80): Max retries exceeded with url: /channel/doChannelList.action (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x191a6d0>, 'Connection to 119.254.9.210 timed out. (connect timeout=6)'))
检测struts2-019超时..
超时原因:  HTTPConnectionPool(host='119.254.9.210', port=80): Max retries exceeded with url: /channel/doChannelList.action (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x191af10>, 'Connection to 119.254.9.210 timed out. (connect timeout=6)'))
检测struts2-devmode超时..

**Comment by gayhub-blackerie** [comment]
巧了这位大兄弟，我也是超时，各种超时。。。。：（请大佬来帮忙科普下啊，不胜感激！

**Comment by starnightcyber** [comment]
因为不是所有的地址都能“正常”访问的啊！
就你给的url而言：目标url:http://119.254.9.210/channel/doChannelList.action
这个地址既不能用浏览器正常访问，也ping不通，在我这是这样。所以超时了！
应该首先对搜集的地址进行过滤，确保连通性没有问题，之后才能检测漏洞。

**Comment by Lucifer1993** [comment]
超时原因很多，从waf阻断，服务器响应和检测url都有关系，先确保给定的链接是可以正常访问的。

**Comment by BlankRain** [comment]
需要登录的怎么办?
