### ISSUE TITLE
无法发现S2-045/046漏洞

### ISSUE THREAD

**Issue by Shad0wpf** [Lucifer1993/struts-scan#8]
Vulhub上的Struts2漏洞环境（http://vulhub.org/#/environments/struts2/s2-016/），同时存在S2-016/045/046漏洞，使用shack2或PKAV的Struts2检测工具均可以发现这三个漏洞，但在Linux环境使用struts-scan-linux，三个漏洞均不能发现。
struts-scan-linux检测结果，Struts2-016提示超时，S2-045/046提示不存在漏洞。通过交互式命令，s2-016可以利用成功，s2-045/46无法利用。

**Comment by Lucifer1993** [comment]
可以把httplib.HTTPConnection._http_vsn = 10
httplib.HTTPConnection._http_vsn_str = 'HTTP/1.0'这两个注释掉再进行测试，因为默认用的HTTP 1.0协议发送请求。

**Comment by Shad0wpf** [comment]
试过注释这两行内容，仍然不能发现。

**Comment by Lucifer1993** [comment]
@Shad0wpf 好的，mark一下

**Comment by zzwlpx** [comment]
您好，我这边有个问题，这里为什么默认采用http1.0，单纯只是为了兼容http1.0吗？

**Comment by houjinhoujin** [comment]
不维护了吗？

**Comment by Lucifer1993** [comment]
python中增加了处理
