### ISSUE TITLE
扫描优化建议

### ISSUE THREAD

**Issue by HatBoy** [Lucifer1993/struts-scan#9]
建议使用click或者其他库优化命令行；整个程序的所有struts漏洞的验证和批量扫描全部是单线程操作，若超时严重会很浪费时间，建议使用多线程优化，有空我自己也优化一下^_^

**Comment by Lucifer1993** [comment]
感谢提议，目前struts漏洞没有以前那么多了，所以重心可能很少放在这上面了。
